apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "burst-scaling-operator.fullname" . }}-manager-role
  labels:
    {{- include "burst-scaling-operator.labels" . | nindent 4 }}
rules:
# BurstScaler CRD
- apiGroups:
  - burstscaling.io
  resources:
  - burstscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - burstscaling.io
  resources:
  - burstscalers/finalizers
  verbs:
  - update
- apiGroups:
  - burstscaling.io
  resources:
  - burstscalers/status
  verbs:
  - get
  - patch
  - update
# KEDA resources (owned children)
- apiGroups:
  - keda.sh
  resources:
  - scaledobjects
  - triggerauthentications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# Read secrets for RabbitMQ credentials
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
# Emit events
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
