# This rule is not used by the project burst-scaling-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the burstscaling.burstscaling.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: burst-scaling-operator
    app.kubernetes.io/managed-by: kustomize
  name: burstscaler-editor-role
rules:
- apiGroups:
  - burstscaling.burstscaling.io
  resources:
  - burstscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - burstscaling.burstscaling.io
  resources:
  - burstscalers/status
  verbs:
  - get
